server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    url: jdbc:mysql://192.168.74.149:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: qwe123
    kikari:
      #      Hikari 连接池配置
      minimum-idle: 5
      #      最小空闲连接数量
      idle-timeout: 180000
      #      空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10
      #      连接池最大连接数，默认是10
      auto-commit: true
      #      此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: MyHikariCP
      #      连接池名称
      max-lifetime: 1800000
      #      此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      #     测试连接是否可用的查询语句
      connection-test-query: SELECT 1
      connection-timeout: 30000
      #      数据库连接超时时间,默认30秒，即30000
  #rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.74.149
    port: 5672
    #开启回调确认
    publisher-confirm-type: correlated
    publisher-returns: false


  redis:
    timeout: 10000ms
    #    host: 127.0.0.1
    host: 192.168.74.149
    port: 6379
    #    数据库
    database: 0
    password: null
    lettuce:
      pool:
        #        最大连接数 默认8
        max-active: 1024
        #        最大连接阻塞等待时间 默认-1
        max-wait: 10000ms
        #        最大空闲连接
        max-idle: 200
        #        最小空闲连接
        min-idle: 5




#mybatis-puls 配置
mybatis-plus:
  #配置mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  configuration:
    map-underscore-to-camel-case: false
  type-aliases-package: com.fz.server.pojo
#mybatis -sql 打印
logging:
  level:
    com.fz.server.mapper: debug


jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24） 24小时
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer



